name: LunaChat
main: com.github.ucchyocean.lc.LunaChat
version: 2.0.0
author: ucchy
description: チャンネルチャットプラグイン
softdepend: [Vault]
commands:
  lunachat:
    description: lunachatのユーザーコマンド
    aliases: [ch, lc]
    usage: |
           /<command> join (channel) - チャンネルに参加します。
           /<command> leave - 参加しているチャンネルから退出します。
           /<command> list - チャンネルのリストを表示します。
           /<command> invite (name) - 指定した人をチャンネルチャットに招待します。
           /<command> accept - 招待を受けてチャンネルチャットに入室します。
           /<command> deny - 招待を拒否します。
           /<command> kick (name) - 指定した人をチャンネルチャットからキックします。
           /<command> ban (name) - 指定した人をチャンネルチャットからBANします。
           /<command> pardon (name) - 指定した人のBANを解除します。
           /<command> info [channel] - チャンネルの情報を表示します。
           /<command> create (channel) - チャンネルを作成します。
           /<command> remove [channel] - チャンネルを削除します。
           /<command> format [channel] (format...) - チャンネルのメッセージフォーマットを設定します。
           /<command> moderator [channel] (player...) - チャンネルのモデレーターを指定したプレイヤーに設定します。
           /<command> option (key=value...) - チャンネルのオプションを設定します。
           /<command> template (number) (template...) - メッセージフォーマットのテンプレートを登録します。
           /<command> reload - config.ymlの再読み込みをします。
  message:
    description: 1:1チャット送信コマンド
    aliases: [msg, tell]
    usage: /<command> (name) [message] - 指定した人との1:1チャットを開始します。
    permission: lunachat.message
    permission-message: パーミッション "<permission>" が無いため、実行できません。
  reply:
    description: 1:1チャット返信コマンド
    aliases: [r]
    usage: /<command> [message] - 受信した1:1チャットに返信します。
    permission: lunachat.reply
    permission-message: パーミッション "<permission>" が無いため、実行できません。
permissions:
  lunachat.join:
    description: joinコマンドの使用権限
  lunachat.leave:
    description: leaveコマンドの使用権限
  lunachat.list:
    description: listコマンドの使用権限
  lunachat.invite:
    description: inviteコマンドの使用権限
  lunachat.accept:
    description: acceptコマンドの使用権限
  lunachat.deny:
    description: denyコマンドの使用権限
  lunachat.kick:
    description: kickコマンドの使用権限
  lunachat.ban:
    description: banコマンドの使用権限
  lunachat.pardon:
    description: pardonコマンドの使用権限
  lunachat.info:
    description: infoコマンドの使用権限
  lunachat.create:
    description: createコマンドの使用権限
  lunachat.remove:
    description: removeコマンドの使用権限
  lunachat.format:
    description: formatコマンドの使用権限
  lunachat.moderator:
    description: moderatorコマンドの使用権限
  lunachat.option:
    description: optionコマンドの使用権限
  lunachat.message:
    description: messageコマンドの使用権限
  lunachat.reply:
    description: replyコマンドの使用権限
  lunachat.*:
    children:
      lunachat.join: true
      lunachat.leave: true
      lunachat.list: true
      lunachat.invite: true
      lunachat.accept: true
      lunachat.deny: true
      lunachat.kick: true
      lunachat.ban: true
      lunachat.pardon: true
      lunachat.info: true
      lunachat.create: true
      lunachat.remove: true
      lunachat.format: true
      lunachat.moderator: true
      lunachat.option: true
      lunachat.message: true
      lunachat.reply: true
    description: 全てのコマンドの使用権限
    default: true
  lunachat.template:
    description: templateコマンドの使用権限
    default: op
  lunachat.reload:
    description: reloadコマンドの使用権限
    default: op
